// Docker Compose File: docker-compose.yml
version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "5002:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

  post-service:
    build:
      context: ./post-service
    ports:
      - "5003:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "5004:5000"
    environment:
      - MONGO_URI=${MONGO_URI}

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"

volumes:
  mongo-data:
